version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started...
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'