# Generated by Django 4.2.7 on 2025-08-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('status', models.CharField(default='Starting...', max_length=200)),
                ('error', models.BooleanField(default=False)),
                ('result_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backtest_progress',
            },
        ),
    ]
